swagger: "2.0"
info:
  description: |
    # Overview
    The Open Charge Point Interface (OCPI) enables a scalable, automated EV roaming setup between Charge Point Operators and e-Mobility Service Providers.
    It supports authorization, charge point information exchange (including live status updates and transaction events), charge detail record exchange, remote charge point commands and, finally, the exchange of smart-charging commands between parties.

    ## OCPI 2.1.1
    During implementation of OCPI 2.1, a number of bugs in the message definition were found.
    This forced us to release a bug fix: OCPI 2.1.1. 
    With the release of OCPI 2.1.1: OCPI 2.1 is deprecated, 2.1 should no longer used and replaced by 2.1.1.
    It should be a small effort to upgrade an existing 2.1 implementation to 2.1.1. 

    For more information on message level changes see [changelog](changelog.md#changelog).


    ## Introduction and background
    The Open Charge Point Interface (OCPI) enables a scalable, automated EV roaming setup between Charge Point Operators and e-Mobility Service Providers. It supports authorization, charge point information exchange (including live status updates and transaction events), charge detail record exchange, remote charge point commands and, finally, the exchange of smart-charging commands between parties.

    It offers market participants in EV an attractive and scalable solution for (international) roaming between networks, avoiding the costs and innovation-limiting complexities involved with today's non-automated solutions or with central roaming hubs.
    As such it helps to enable EV drivers to charge everywhere in a fully-informed way, helps the market to develop quickly and helps market players to execute their business models in the best way.

    What does it offer (main functionalities):
    * A good roaming system (for bilateral usage and/or via a hub).
    * Real-time information about location, availability and price.
    * A uniform way of exchanging data (Notification Data Records and Charge Data Records), before during and after the transaction.
    * Remote mobile support to access any charge station without pre-registration.

    Starting in 2009, e-laad foundation and the predecessor of the eViolin association specified 2 standards in order to retrieve charge point details and active state. These are called the VAS interface and the Amsterdam interface. In this same period, a CDR format for the exchange of charge sessions between eViolin members was defined. This format is currently in use by the majority of the eViolin members. (eViolin is the branch organisation for EV operators and service providers in NL and responsible for national roaming and issuing of ID’s). This resulted in 2014 in the development of OCPI.

    An international group of companies already supports OCPI. Initiators are EV Box, The New Motion, ElaadNL, BeCharged, Greenflux and Last Mile Solutions. Other participants include Next Charge, Freshmile, Plugsurfing, Charge-partner, Hubject, e-clearing.net, IHomer and Siemens. Several other major organizations and roaming platforms are interested in participating. The Netherlands Knowledge Platform for Charging Infrastructure (NKL) facilitates and coordinates this project to guarantee progress and ensure development and results. Part of this project is to find a place to continue development in the future.

    This document describes a combined set of standards based on the work done in the past. Next to that, the evolution of these standards and their use is taken into account and some elements have been updated to match nowadays use.

  version: "2.1.1"
  title: "OCPI Specification API"
host: "example.com"
basePath: "/ocpi/cpo/"
tags:
  - name: "versions"
  - name: "version-details"
consumes:
  - "application/json"
produces:
  - "application/json"
schemes:
  - "https"
  - "http"
externalDocs:
  description: "Find out more about OCPI"
  url: "https://github.com/ocpi/ocpi"

#############
### Endpoints
#############

paths:
  /versions:
    get:
      tags:
        - "versions"
      summary: "Version information"
      description: |
        This endpoint lists all the available OCPI versions and the corresponding URLs to where version specific details such as the supported endpoints can be found.
        Example endpoint structure: `ocpi/cpo/versions` and `/ocpi/emsp/versions`
        The exact URL to the implemented version endpoint should be given (offline) to parties that interface with your OCPI implementation, this endpoint is the starting point for discovering locations of the different modules and version of OCPI that have been implemented.
        Both the CPO and the eMSP must have this endpoint.
      consumes:
        - "application/json"
      produces:
        - "application/json"

      responses:
        200:
          description: OK
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Version"

  /{version}:
    get:
      tags:
        - "version-details"
      summary: "Fetch information about the supported endpoints for this version."
      description: |
        This endpoint lists the supported endpoints and their URLs for a specific OCPI version. To notify the other party that the list of endpoints of your current version has changed, you can send a PUT request to the corresponding credentials endpoint (see the credentials chapter).

        Both the CPO and the eMSP must have this endpoint.
      parameters:
        - name: "version"
          in: "path"
          description: The version number
          required: true
          type: "string"

      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/VersionDetail"

#############
### Definitions
#############

definitions:
  Version:
    type: "object"
    properties:
      version:
        type: "string"
        example: "2.1.1"
      url:
        type: "string"
        example: "https://example.com/ocpi/cpo/2.1.1/"

  VersionDetail:
    type: "object"
    properties:
      version:
        type: "string"
        description: The Module identifiers for each endpoint are in the beginning of each *Module* chapter. The following table contains the list of modules in this version of OCPI. Most modules (except [Credentials & registration](credentials.md#credentials-endpoint)) are optional, but there might be dependencies between modules, if so that will be mentioned in the module description.
        example: "2.1.1"
      endpoints:
        type: "array"
        items:
          $ref: "#/definitions/Endpoint"

  Endpoint:
    type: "object"
    properties:
      identifier:
        type: "string"
        $ref: "#/definitions/ModuleID"
      url:
        type: "string"
        example: "https://example.com/ocpi/cpo/2.0/credentials/"

  ModuleID:
    type: "string"
    enum: 
     - cdrs
     - commands
     - credentials
     - locations
     - sessions
     - tariffs
     - tokens
    example: "credentials"

